/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as NotAllowedIndexImport } from './routes/not-allowed/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedTrackerIndexImport } from './routes/_authenticated/tracker/index'
import { Route as AuthenticatedPrintNumberIndexImport } from './routes/_authenticated/print-number/index'
import { Route as AuthenticatedManajemenUserIndexImport } from './routes/_authenticated/manajemen-user/index'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDaftarBarangIndexImport } from './routes/_authenticated/daftar-barang/index'
import { Route as AuthenticatedAnggaranIndexImport } from './routes/_authenticated/anggaran/index'
import { Route as AuthenticatedAktivitasLogIndexImport } from './routes/_authenticated/aktivitas-log/index'
import { Route as AuthenticatedPengajuanIdIndexImport } from './routes/_authenticated/pengajuan/$id/index'
import { Route as AuthenticatedPengadaanOrgIdIndexImport } from './routes/_authenticated/pengadaan/$orgId/index'

// Create Virtual Routes

const AuthLoginIndexLazyImport = createFileRoute('/_auth/login/')()
const AuthAuthResponseIndexLazyImport = createFileRoute(
  '/_auth/auth-response/',
)()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotAllowedIndexRoute = NotAllowedIndexImport.update({
  id: '/not-allowed/',
  path: '/not-allowed/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthLoginIndexLazyRoute = AuthLoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/login/index.lazy').then((d) => d.Route),
)

const AuthAuthResponseIndexLazyRoute = AuthAuthResponseIndexLazyImport.update({
  id: '/auth-response/',
  path: '/auth-response/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/auth-response/index.lazy').then((d) => d.Route),
)

const AuthenticatedTrackerIndexRoute = AuthenticatedTrackerIndexImport.update({
  id: '/tracker/',
  path: '/tracker/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPrintNumberIndexRoute =
  AuthenticatedPrintNumberIndexImport.update({
    id: '/print-number/',
    path: '/print-number/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/print-number/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedManajemenUserIndexRoute =
  AuthenticatedManajemenUserIndexImport.update({
    id: '/manajemen-user/',
    path: '/manajemen-user/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/manajemen-user/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dashboard/index.lazy').then((d) => d.Route),
  )

const AuthenticatedDaftarBarangIndexRoute =
  AuthenticatedDaftarBarangIndexImport.update({
    id: '/daftar-barang/',
    path: '/daftar-barang/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/daftar-barang/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAnggaranIndexRoute = AuthenticatedAnggaranIndexImport.update(
  {
    id: '/anggaran/',
    path: '/anggaran/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import('./routes/_authenticated/anggaran/index.lazy').then((d) => d.Route),
)

const AuthenticatedAktivitasLogIndexRoute =
  AuthenticatedAktivitasLogIndexImport.update({
    id: '/aktivitas-log/',
    path: '/aktivitas-log/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/aktivitas-log/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedPengajuanIdIndexRoute =
  AuthenticatedPengajuanIdIndexImport.update({
    id: '/pengajuan/$id/',
    path: '/pengajuan/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/pengajuan/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedPengadaanOrgIdIndexRoute =
  AuthenticatedPengadaanOrgIdIndexImport.update({
    id: '/pengadaan/$orgId/',
    path: '/pengadaan/$orgId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/pengadaan/$orgId/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/not-allowed/': {
      id: '/not-allowed/'
      path: '/not-allowed'
      fullPath: '/not-allowed'
      preLoaderRoute: typeof NotAllowedIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/aktivitas-log/': {
      id: '/_authenticated/aktivitas-log/'
      path: '/aktivitas-log'
      fullPath: '/aktivitas-log'
      preLoaderRoute: typeof AuthenticatedAktivitasLogIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/anggaran/': {
      id: '/_authenticated/anggaran/'
      path: '/anggaran'
      fullPath: '/anggaran'
      preLoaderRoute: typeof AuthenticatedAnggaranIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/daftar-barang/': {
      id: '/_authenticated/daftar-barang/'
      path: '/daftar-barang'
      fullPath: '/daftar-barang'
      preLoaderRoute: typeof AuthenticatedDaftarBarangIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/manajemen-user/': {
      id: '/_authenticated/manajemen-user/'
      path: '/manajemen-user'
      fullPath: '/manajemen-user'
      preLoaderRoute: typeof AuthenticatedManajemenUserIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/print-number/': {
      id: '/_authenticated/print-number/'
      path: '/print-number'
      fullPath: '/print-number'
      preLoaderRoute: typeof AuthenticatedPrintNumberIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/tracker/': {
      id: '/_authenticated/tracker/'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/auth-response/': {
      id: '/_auth/auth-response/'
      path: '/auth-response'
      fullPath: '/auth-response'
      preLoaderRoute: typeof AuthAuthResponseIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/pengadaan/$orgId/': {
      id: '/_authenticated/pengadaan/$orgId/'
      path: '/pengadaan/$orgId'
      fullPath: '/pengadaan/$orgId'
      preLoaderRoute: typeof AuthenticatedPengadaanOrgIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/pengajuan/$id/': {
      id: '/_authenticated/pengajuan/$id/'
      path: '/pengajuan/$id'
      fullPath: '/pengajuan/$id'
      preLoaderRoute: typeof AuthenticatedPengajuanIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthResponseIndexLazyRoute: typeof AuthAuthResponseIndexLazyRoute
  AuthLoginIndexLazyRoute: typeof AuthLoginIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthResponseIndexLazyRoute: AuthAuthResponseIndexLazyRoute,
  AuthLoginIndexLazyRoute: AuthLoginIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAktivitasLogIndexRoute: typeof AuthenticatedAktivitasLogIndexRoute
  AuthenticatedAnggaranIndexRoute: typeof AuthenticatedAnggaranIndexRoute
  AuthenticatedDaftarBarangIndexRoute: typeof AuthenticatedDaftarBarangIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedManajemenUserIndexRoute: typeof AuthenticatedManajemenUserIndexRoute
  AuthenticatedPrintNumberIndexRoute: typeof AuthenticatedPrintNumberIndexRoute
  AuthenticatedTrackerIndexRoute: typeof AuthenticatedTrackerIndexRoute
  AuthenticatedPengadaanOrgIdIndexRoute: typeof AuthenticatedPengadaanOrgIdIndexRoute
  AuthenticatedPengajuanIdIndexRoute: typeof AuthenticatedPengajuanIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAktivitasLogIndexRoute: AuthenticatedAktivitasLogIndexRoute,
  AuthenticatedAnggaranIndexRoute: AuthenticatedAnggaranIndexRoute,
  AuthenticatedDaftarBarangIndexRoute: AuthenticatedDaftarBarangIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedManajemenUserIndexRoute: AuthenticatedManajemenUserIndexRoute,
  AuthenticatedPrintNumberIndexRoute: AuthenticatedPrintNumberIndexRoute,
  AuthenticatedTrackerIndexRoute: AuthenticatedTrackerIndexRoute,
  AuthenticatedPengadaanOrgIdIndexRoute: AuthenticatedPengadaanOrgIdIndexRoute,
  AuthenticatedPengajuanIdIndexRoute: AuthenticatedPengajuanIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedDashboardRoute
  '/not-allowed': typeof NotAllowedIndexRoute
  '/aktivitas-log': typeof AuthenticatedAktivitasLogIndexRoute
  '/anggaran': typeof AuthenticatedAnggaranIndexRoute
  '/daftar-barang': typeof AuthenticatedDaftarBarangIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/manajemen-user': typeof AuthenticatedManajemenUserIndexRoute
  '/print-number': typeof AuthenticatedPrintNumberIndexRoute
  '/tracker': typeof AuthenticatedTrackerIndexRoute
  '/auth-response': typeof AuthAuthResponseIndexLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/pengadaan/$orgId': typeof AuthenticatedPengadaanOrgIdIndexRoute
  '/pengajuan/$id': typeof AuthenticatedPengajuanIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedDashboardRoute
  '/not-allowed': typeof NotAllowedIndexRoute
  '/aktivitas-log': typeof AuthenticatedAktivitasLogIndexRoute
  '/anggaran': typeof AuthenticatedAnggaranIndexRoute
  '/daftar-barang': typeof AuthenticatedDaftarBarangIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/manajemen-user': typeof AuthenticatedManajemenUserIndexRoute
  '/print-number': typeof AuthenticatedPrintNumberIndexRoute
  '/tracker': typeof AuthenticatedTrackerIndexRoute
  '/auth-response': typeof AuthAuthResponseIndexLazyRoute
  '/login': typeof AuthLoginIndexLazyRoute
  '/pengadaan/$orgId': typeof AuthenticatedPengadaanOrgIdIndexRoute
  '/pengajuan/$id': typeof AuthenticatedPengajuanIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRoute
  '/not-allowed/': typeof NotAllowedIndexRoute
  '/_authenticated/aktivitas-log/': typeof AuthenticatedAktivitasLogIndexRoute
  '/_authenticated/anggaran/': typeof AuthenticatedAnggaranIndexRoute
  '/_authenticated/daftar-barang/': typeof AuthenticatedDaftarBarangIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/manajemen-user/': typeof AuthenticatedManajemenUserIndexRoute
  '/_authenticated/print-number/': typeof AuthenticatedPrintNumberIndexRoute
  '/_authenticated/tracker/': typeof AuthenticatedTrackerIndexRoute
  '/_auth/auth-response/': typeof AuthAuthResponseIndexLazyRoute
  '/_auth/login/': typeof AuthLoginIndexLazyRoute
  '/_authenticated/pengadaan/$orgId/': typeof AuthenticatedPengadaanOrgIdIndexRoute
  '/_authenticated/pengajuan/$id/': typeof AuthenticatedPengajuanIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/not-allowed'
    | '/aktivitas-log'
    | '/anggaran'
    | '/daftar-barang'
    | '/dashboard'
    | '/manajemen-user'
    | '/print-number'
    | '/tracker'
    | '/auth-response'
    | '/login'
    | '/pengadaan/$orgId'
    | '/pengajuan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/not-allowed'
    | '/aktivitas-log'
    | '/anggaran'
    | '/daftar-barang'
    | '/dashboard'
    | '/manajemen-user'
    | '/print-number'
    | '/tracker'
    | '/auth-response'
    | '/login'
    | '/pengadaan/$orgId'
    | '/pengajuan/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/_dashboard'
    | '/not-allowed/'
    | '/_authenticated/aktivitas-log/'
    | '/_authenticated/anggaran/'
    | '/_authenticated/daftar-barang/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/manajemen-user/'
    | '/_authenticated/print-number/'
    | '/_authenticated/tracker/'
    | '/_auth/auth-response/'
    | '/_auth/login/'
    | '/_authenticated/pengadaan/$orgId/'
    | '/_authenticated/pengajuan/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NotAllowedIndexRoute: typeof NotAllowedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NotAllowedIndexRoute: NotAllowedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_authenticated",
        "/not-allowed/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth-response/",
        "/_auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_dashboard",
        "/_authenticated/aktivitas-log/",
        "/_authenticated/anggaran/",
        "/_authenticated/daftar-barang/",
        "/_authenticated/dashboard/",
        "/_authenticated/manajemen-user/",
        "/_authenticated/print-number/",
        "/_authenticated/tracker/",
        "/_authenticated/pengadaan/$orgId/",
        "/_authenticated/pengajuan/$id/"
      ]
    },
    "/_authenticated/_dashboard": {
      "filePath": "_authenticated/_dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/not-allowed/": {
      "filePath": "not-allowed/index.tsx"
    },
    "/_authenticated/aktivitas-log/": {
      "filePath": "_authenticated/aktivitas-log/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/anggaran/": {
      "filePath": "_authenticated/anggaran/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/daftar-barang/": {
      "filePath": "_authenticated/daftar-barang/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/manajemen-user/": {
      "filePath": "_authenticated/manajemen-user/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/print-number/": {
      "filePath": "_authenticated/print-number/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tracker/": {
      "filePath": "_authenticated/tracker/index.tsx",
      "parent": "/_authenticated"
    },
    "/_auth/auth-response/": {
      "filePath": "_auth/auth-response/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/pengadaan/$orgId/": {
      "filePath": "_authenticated/pengadaan/$orgId/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pengajuan/$id/": {
      "filePath": "_authenticated/pengajuan/$id/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
